---
version: '3'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=bitchange
      - POSTGRES_USER=bitchange
      - POSTGRES_PASSWORD=bitchange

  web:
    build:
      context: ./backend
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - exclude:/app/node_modules/

volumes:
    exclude:
