---
version: '3'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=bitchange
      - POSTGRES_USER=bitchange
      - POSTGRES_PASSWORD=bitchange
    
  web:
    build:
      context: ./backend
      dockerfile: ./docker/local/Dockerfile
    env_file:
      - .env.local
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
