---
name: bin

on: [push]

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install yamllint
      - name: Run yamllint
        run: yamllint .
